#!/usr/bin/env python3
"""Generate docs/api-reference.md from the public agent_contracts exports."""

from __future__ import annotations

import argparse
import inspect
from pathlib import Path
from typing import Any, Iterable, List

import agent_contracts

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "api-reference.md"


def _kind(obj: Any) -> str:
    if inspect.isclass(obj):
        if issubclass(obj, BaseException):
            return "exception"
        return "class"
    if inspect.isfunction(obj):
        return "function"
    return "constant"


def _signature(obj: Any) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return ""


def _summary(name: str, obj: Any) -> str:
    if name == "__version__":
        return "Installed package version string."
    doc = inspect.getdoc(obj) or "No public docstring yet."
    return " ".join(doc.split("\n\n", 1)[0].split())


def _render_symbol(name: str, obj: Any) -> List[str]:
    kind = _kind(obj)
    signature = _signature(obj)
    module = getattr(obj, "__module__", "agent_contracts")
    lines = [
        f"### `{name}`",
        "",
        f"- Kind: `{kind}`",
        f"- Import: `from agent_contracts import {name}`",
    ]
    if module and module != "builtins":
        lines.append(f"- Source module: `{module}`")
    if signature and kind in {"class", "function", "exception"}:
        lines.append(f"- Signature: `{name}{signature}`")
    if name == "__version__":
        lines.append(f"- Current source value: `{obj}`")
    lines.extend(["", _summary(name, obj), ""])
    return lines


def render_reference(names: Iterable[str]) -> str:
    lines: List[str] = [
        "# Agent Contracts API Reference",
        "",
        "> Generated by `python scripts/generate_api_reference.py`. Do not edit this file by hand.",
        "",
        "Published path after merge: https://github.com/pyyush/agentcontracts/blob/main/docs/api-reference.md",
        "",
        "This page documents the stable public imports promised by `agent_contracts.__all__` for the `1.0.0` release train.",
        "",
    ]
    for name in names:
        lines.extend(_render_symbol(name, getattr(agent_contracts, name)))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if docs/api-reference.md is stale.")
    args = parser.parse_args()

    rendered = render_reference(agent_contracts.__all__)
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            print(f"{OUTPUT} is stale. Run python scripts/generate_api_reference.py.")
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
